{
  "version": "1.2",
  "dbname": "database.fasta",
  "dbtype": "Nucleotide",
  "db-version": 5,
  "description": "database.fasta",
  "number-of-letters": 3056855431,
  "number-of-sequences": 1027357,
  "last-updated": "2022-12-21T12:44:00",
  "number-of-volumes": 16,
  "bytes-total": 917233056,
  "bytes-to-cache": 778346506,
  "files": [
    "database.fasta.00.nhr",
    "database.fasta.00.nin",
    "database.fasta.00.nsq",
    "database.fasta.01.nhr",
    "database.fasta.01.nin",
    "database.fasta.01.nsq",
    "database.fasta.02.nhr",
    "database.fasta.02.nin",
    "database.fasta.02.nsq",
    "database.fasta.03.nhr",
    "database.fasta.03.nin",
    "database.fasta.03.nsq",
    "database.fasta.04.nhr",
    "database.fasta.04.nin",
    "database.fasta.04.nsq",
    "database.fasta.05.nhr",
    "database.fasta.05.nin",
    "database.fasta.05.nsq",
    "database.fasta.06.nhr",
    "database.fasta.06.nin",
    "database.fasta.06.nsq",
    "database.fasta.07.nhr",
    "database.fasta.07.nin",
    "database.fasta.07.nsq",
    "database.fasta.08.nhr",
    "database.fasta.08.nin",
    "database.fasta.08.nsq",
    "database.fasta.09.nhr",
    "database.fasta.09.nin",
    "database.fasta.09.nsq",
    "database.fasta.10.nhr",
    "database.fasta.10.nin",
    "database.fasta.10.nsq",
    "database.fasta.11.nhr",
    "database.fasta.11.nin",
    "database.fasta.11.nsq",
    "database.fasta.12.nhr",
    "database.fasta.12.nin",
    "database.fasta.12.nsq",
    "database.fasta.13.nhr",
    "database.fasta.13.nin",
    "database.fasta.13.nsq",
    "database.fasta.14.nhr",
    "database.fasta.14.nin",
    "database.fasta.14.nsq",
    "database.fasta.15.nhr",
    "database.fasta.15.nin",
    "database.fasta.15.nsq",
    "database.fasta.nal",
    "database.fasta.ndb",
    "database.fasta.not",
    "database.fasta.ntf",
    "database.fasta.nto"
  ]
}
